### ISSUE TITLE
Package can't be used effectively during development

### ISSUE THREAD

**Issue by colbin8r** [outpunk/grunt-evil-icons#1]
Hey guys! I'm a huge fan of the Evil Icon set--gorgeous, clean, and scalable.

I ran into a problem trying to use the icons via grunt package on my latest project. I don't understand how to incorporate it into my single page JavaScript app. If I run the package as a part of the build process, I can't preview my icons during development. If I runt the package as a part of a `grunt watch` on my HTML file, every time I change the HTML, the entire SVG code is duplicated--you can imagine how messy it gets after 5-6 edits.

Do you have any suggestions as to how best use this package during active development?

**Comment by madyankin** [comment]
Hey, thanks for the feedback! Is the only sprite being duplicated? Could you show me a sample config?

**Comment by madyankin** [comment]
@colbin8r Hello, I've just fixed this. The new version is in npm. Sorry for the late fix and thank you for the report.

**Comment by colbin8r** [comment]
@outpunk thanks for the fix. I have yet to try it out--unfortunately, the issue lead to me temporarily abandoning the project. Now that it's fixed, I'll be sure to revisit!
